//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.ClassSubjects = new HashSet<ClassSubject>();
            this.ClassSections = new HashSet<ClassSection>();
            this.StudentClassSectionInfoes = new HashSet<StudentClassSectionInfo>();
            this.Hours = new HashSet<Hour>();
        }
    
        public int Id { get; set; }
        public string ClassName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Blocked { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
    
        public virtual ICollection<ClassSubject> ClassSubjects { get; set; }
        public virtual ICollection<ClassSection> ClassSections { get; set; }
        public virtual ICollection<StudentClassSectionInfo> StudentClassSectionInfoes { get; set; }
        public virtual ICollection<Hour> Hours { get; set; }
    }
}
