//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.States = new HashSet<State>();
            this.Addresses = new HashSet<Address>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
