//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttendance
    {
        public DailyAttendance()
        {
            this.HourlyAttendances = new HashSet<HourlyAttendance>();
        }
    
        public int Id { get; set; }
        public int StudentId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Remarks { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ICollection<HourlyAttendance> HourlyAttendances { get; set; }
    }
}
