//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyContactDetail
    {
        public EmergencyContactDetail()
        {
            this.StudentAditionalInfoes = new HashSet<StudentAditionalInfo>();
        }
    
        public int Id { get; set; }
        public string ContactPersonName { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string Relationship { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool Blocked { get; set; }
    
        public virtual ICollection<StudentAditionalInfo> StudentAditionalInfoes { get; set; }
    }
}
