//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamMarks
    {
        public int Id { get; set; }
        public int ExamSubjectScheduleId { get; set; }
        public int StudentID { get; set; }
        public int Marks { get; set; }
        public Nullable<int> Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Blocked { get; set; }
    
        public virtual ExamSubjectSchedule ExamSubjectSchedule { get; set; }
    }
}
