//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSubjectSchedule
    {
        public int Id { get; set; }
        public int ExamScheduleId { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }
        public System.DateTime ExamDateTime { get; set; }
        public int Duration { get; set; }
        public int MinMarks { get; set; }
        public int MaxMarks { get; set; }
        public int PassMarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Blocked { get; set; }
    
        public virtual ExamMarks ExamMark { get; set; }
        public virtual ExamSchedule ExamSchedule { get; set; }
    }
}
