//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSchedule
    {
        public ExamSchedule()
        {
            this.ExamSubjectSchedules = new HashSet<ExamSubjectSchedule>();
        }
    
        public int Id { get; set; }
        public int ExamID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TotalMarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Blocked { get; set; }
    
        public virtual ICollection<ExamSubjectSchedule> ExamSubjectSchedules { get; set; }
        public virtual Exam Exam { get; set; }
    }
}
