//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public Institution()
        {
            this.StudentClassSectionInfoes = new HashSet<StudentClassSectionInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string RegName { get; set; }
        public string RegNo { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string Type { get; set; }
        public Nullable<int> AddressId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool Blocked { get; set; }
    
        public virtual ICollection<StudentClassSectionInfo> StudentClassSectionInfoes { get; set; }
    }
}
