//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.StudentAditionalInfoes = new HashSet<StudentAditionalInfo>();
        }
    
        public int Id { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PhoneNo { get; set; }
        public string EmailId { get; set; }
        public int UserTypeId { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> BlockedDate { get; set; }
        public Nullable<bool> isBlocked { get; set; }
        public Nullable<int> BlockedBy { get; set; }
    
        public virtual ICollection<StudentAditionalInfo> StudentAditionalInfoes { get; set; }
    }
}
