//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.ClassSections = new HashSet<ClassSection>();
            this.StudentClassSectionInfoes = new HashSet<StudentClassSectionInfo>();
        }
    
        public int Id { get; set; }
        public string SectionName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Blocked { get; set; }
    
        public virtual ICollection<ClassSection> ClassSections { get; set; }
        public virtual ICollection<StudentClassSectionInfo> StudentClassSectionInfoes { get; set; }
    }
}
