//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Parents = new HashSet<Parent>();
            this.StudentAddresses = new HashSet<StudentAddress>();
            this.StudentClassSectionInfoes = new HashSet<StudentClassSectionInfo>();
            this.StudentAditionalInfoes = new HashSet<StudentAditionalInfo>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Blocked { get; set; }
    
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual ICollection<StudentAddress> StudentAddresses { get; set; }
        public virtual ICollection<StudentClassSectionInfo> StudentClassSectionInfoes { get; set; }
        public virtual ICollection<StudentAditionalInfo> StudentAditionalInfoes { get; set; }
    }
}
