//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAditionalInfo
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> Address1Id { get; set; }
        public Nullable<int> Address2Id { get; set; }
        public string AdmissionNo { get; set; }
        public string ClassRollNo { get; set; }
        public Nullable<System.DateTime> AddmissionDate { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string BirthPlace { get; set; }
        public string Nationalty { get; set; }
        public string Language { get; set; }
        public string Religion { get; set; }
        public string StudentCategory { get; set; }
        public Nullable<bool> IsSMSEnabled { get; set; }
        public string PhotoFileName { get; set; }
        public string PhotoContentType { get; set; }
        public byte[] PhotoData { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<int> EmergencyContactDetailsID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual EmergencyContactDetail EmergencyContactDetail { get; set; }
        public virtual Student Student { get; set; }
    }
}
