//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuentClassSectionInfo
    {
        public int Id { get; set; }
        public int StuentID { get; set; }
        public Nullable<int> StudentNo { get; set; }
        public int ClassID { get; set; }
        public int SectionID { get; set; }
        public string RollNo { get; set; }
        public string Meadium { get; set; }
        public int InstitutionID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Blocked { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual InstitutionInfo InstitutionInfo { get; set; }
        public virtual Section Section { get; set; }
    }
}
