//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubDistrict
    {
        public int SubDistrictsId { get; set; }
        public string SubDistrictsName { get; set; }
        public int DistrictId { get; set; }
    
        public virtual District District { get; set; }
    }
}
