//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.ClassSubjects = new HashSet<ClassSubject>();
            this.TeacherSubjects = new HashSet<TeacherSubject>();
        }
    
        public int Id { get; set; }
        public string SubjectName { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> locationID { get; set; }
    
        public virtual ICollection<ClassSubject> ClassSubjects { get; set; }
        public virtual ICollection<TeacherSubject> TeacherSubjects { get; set; }
    }
}
